services:
  jitsi-web:
    image: jitsi/web:stable-9823
    container_name: jitsi-web
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENABLE_AUTH=1
      - AUTH_TYPE=jwt
      - JWT_APP_ID=${JWT_APP_ID}
      - JWT_APP_SECRET=${JWT_APP_SECRET}
      - JWT_ACCEPTED_ISSUERS=meettrack
      - JWT_ACCEPTED_AUDIENCES=jitsi
      - PUBLIC_URL=https://${JITSI_DOMAIN}
      - XMPP_RECORDER_DOMAIN=hidden.meet.jitsi
      - TZ=Asia/Tashkent
    volumes:
      - ${CONFIG}/web:/config:Z
      - ${CONFIG}/web/crontabs:/var/spool/cron/crontabs:Z
      - ${CONFIG}/transcripts:/usr/share/jitsi-meet/transcripts:Z
    networks:
      meet.jitsi:

  prosody:
    image: jitsi/prosody:stable-9823
    container_name: jitsi-prosody
    restart: unless-stopped
    environment:
      - ENABLE_AUTH=1
      - AUTH_TYPE=jwt
      - JWT_APP_ID=${JWT_APP_ID}
      - JWT_APP_SECRET=${JWT_APP_SECRET}
      - JWT_ACCEPTED_ISSUERS=meettrack
      - JWT_ACCEPTED_AUDIENCES=jitsi
      - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
      - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
      - ENABLE_RECORDING=1
      - XMPP_RECORDER_DOMAIN=hidden.meet.jitsi
      - XMPP_MUC_MODULES=muc_hidden_occ
      - JIBRI_XMPP_USER=jibri
      - JIBRI_XMPP_PASSWORD=${JIBRI_XMPP_PASSWORD}
      - JIBRI_RECORDER_USER=recorder
      - JIBRI_RECORDER_PASSWORD=${JIBRI_RECORDER_PASSWORD}
      - TZ=Asia/Tashkent
    ports:
      - "10.120.4.15:5222:5222"
    volumes:
      - ${CONFIG}/prosody/config:/config:Z
      - ${CONFIG}/prosody/prosody-plugins-custom:/prosody-plugins-custom:Z
    networks:
      meet.jitsi:
        aliases:
          - xmpp.meet.jitsi

  jicofo:
    image: jitsi/jicofo:stable-9823
    container_name: jitsi-jicofo
    restart: unless-stopped
    environment:
      - AUTH_TYPE=jwt
      - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
      - ENABLE_RECORDING=1
      - XMPP_RECORDER_DOMAIN=hidden.meet.jitsi
      - TZ=Asia/Tashkent
    volumes:
      - ${CONFIG}/jicofo:/config:Z
    depends_on:
      - prosody
    networks:
      meet.jitsi:

  jvb:
    image: jitsi/jvb:stable-9823
    container_name: jitsi-jvb
    restart: unless-stopped
    ports:
      - "10000:10000/udp"
    environment:
      - JVB_PORT=10000
      - JVB_ADVERTISE_IPS=${JVB_ADVERTISE_IPS}
      - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
      - TZ=Asia/Tashkent
    volumes:
      - ${CONFIG}/jvb:/config:Z
    depends_on:
      - prosody
    networks:
      meet.jitsi:

networks:
  meet.jitsi:
